name: Continuous Integration
on: [pull_request]

jobs:
  build:
    name: Run unit tests with Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.11.0"
          cache: 'npm'
      - name: Setup GIT for testing
        run: git config --global user.email "cplace-npm-tools@cplace.io" && git config --global user.name "cplace-npm-tools GitHub Action"
      - name: Install modules
        run: npm install && npm install -g jest
      - name: Run Jest
        run: jest --verbose
